### ISSUE TITLE
[BUG]: Strings and constants have almost the same colour

### ISSUE THREAD

**Issue by max-programming** [AnishDe12020/orbi#1]
### Description of the bug

The strings and the constants have almost the same colour

### Steps To Reproduce

Create a constant, and a template literal or a string

### Additional Information

![image](https://user-images.githubusercontent.com/51731966/179400926-0a83b1bc-a576-46f0-a077-00d7afe38e29.png)

**Comment by AnishDe12020** [comment]
Changed the color of the string, this is better?

![image](https://user-images.githubusercontent.com/63192115/179401845-4c46d411-17a8-4bf3-a9b4-dfe7dd504dcb.png)
![image](https://user-images.githubusercontent.com/63192115/179401862-d2f027d0-b691-431d-83e4-54e1899b966b.png)

**Comment by max-programming** [comment]
A lot better. Also the constant looks a little dull. Woudl be better to increase the whiteness of it

**Comment by AnishDe12020** [comment]
I made a small change to the green (looked a lil dull)
![image](https://user-images.githubusercontent.com/63192115/179402081-add6bc8a-ba0a-4904-ad80-ed095c1c5241.png)

Ill look into the const color

**Comment by AnishDe12020** [comment]
![image](https://user-images.githubusercontent.com/63192115/179402331-de68da69-56cb-4715-beec-92872a24859c.png)
![image](https://user-images.githubusercontent.com/63192115/179402337-4d02c19a-98ad-4fa0-ad7a-2dd5e1b9336a.png)


~~let me know if this is good~~ pushed and published lol, you gotta update the theme ig

**Comment by max-programming** [comment]
Yep looks good now :v:
